### ISSUE TITLE
[Bug] “Download skipped, since file exists” endless loop

### ISSUE THREAD

**Issue by maxboz** [exislow/tidal-dl-ng#287]
### What happened?

After downloading about 20 albums, the app downloads an album and enters a loop saying “Download skipped, since file exists,” preventing it from downloading the next one. This issue consumes RAM and makes the UI unresponsive. The only solution is to close the app and re-add the queue. 

### Version App

0.23.0

### What operating system are you seeing the problem on?

macOS

### Your settings

```json
{
    "skip_existing": true,
    "lyrics_embed": false,
    "lyrics_file": false,
    "video_download": false,
    "download_delay": true,
    "download_base_path": "/Volumes/MUSIC/",
    "quality_audio": "HI_RES_LOSSLESS",
    "quality_video": "480",
    "format_album": "{album_artist}/{album_title}/{track_volume_num_optional}{album_track_num}. {artist_name} - {track_title}{album_explicit}",
    "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}",
    "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}",
    "format_track": "{artist_name}/{track_title}{track_explicit}",
    "format_video": "Videos/{artist_name} - {track_title}{track_explicit}",
    "video_convert_mp4": false,
    "path_binary_ffmpeg": "/opt/homebrew/bin/ffmpeg",
    "metadata_cover_dimension": "320",
    "metadata_cover_embed": true,
    "cover_album_file": true,
    "extract_flac": true,
    "downloads_simultaneous_per_track_max": 20,
    "download_delay_sec_min": 3.0,
    "download_delay_sec_max": 5.0,
    "album_track_num_pad_min": 1,
    "downloads_concurrent_max": 5,
    "symlink_to_track": false,
    "playlist_create": false
}
```

**Comment by exislow** [comment]
Thanks for reporting this. It should be already fixed in master branch. Cannot release it, since this fix is not yet released https://github.com/tamland/python-tidal/issues/309

**Comment by ryoko7** [comment]
> Thanks for reporting this. It should be already fixed in master branch. Cannot release it, since this fix is not yet released [tamland/python-tidal#309](https://github.com/tamland/python-tidal/)

Great work on this repository. Hey, are you aware if pip install git+(this repo) will compile your fork of python-tidal? Or does it still try to get python-tidal from tamland's repo?

**Comment by exislow** [comment]
What do you exactly mean? I actually need to push a release to PyPi. But this does not work with git linked sources in `pyproject.toml`.

**Comment by ryoko7** [comment]
I've been downloading with `pip install git+https://github.com/exislow/tidal-dl-ng.git`
Works great and it includes your (formatted) extended file detection commits

**Comment by exislow** [comment]
Can you confirm that this is fixed with the latest version?

**Comment by maxboz** [comment]
Hi, my issue appears to be fixed - I've had no issues with the new version so far. I've tested it with around 25 albums, and if anything breaks in the future, I'll let you know. Thank you so much for your support!

**Comment by ZomkaDEV** [comment]
I am still experiencing this issue on the latest stable version (0.24.6) on Windows (10). Usually happens after an album fails to download.
