### ISSUE TITLE
Videos Not Downloading

### ISSUE THREAD

**Issue by DJ-BAD** [exislow/tidal-dl-ng#386]
### You must use the search before you create an issue!

- [x] I did use the search, I promise!

### I need Help.

I have searched for Videos & Used The Download Function. It will say "download Started" & "Download Finish" But The File Is not in my Downloads Folder or anywhere on my computer. I have downloaded ffmpeg & audio downloads are working flawlessly.

### What operating system do you use?

macOS

### Version OS

MacOS 15.3.2

### Your settings

```json
{
    "skip_existing": true,
    "lyrics_embed": false,
    "lyrics_file": false,
    "video_download": true,
    "download_delay": true,
    "download_base_path": "/Users/bad/Downloads/Tidal Downloads",
    "quality_audio": "HI_RES_LOSSLESS",
    "quality_video": "1080",
    "format_album": "Albums/{album_artist} - {album_title}{album_explicit}/{track_volume_num_optional}{album_track_num}. {artist_name} - {track_title}{album_explicit}",
    "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}",
    "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}",
    "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}",
    "format_video": "Videos/{artist_name} - {track_title}{track_explicit}",
    "video_convert_mp4": true,
    "path_binary_ffmpeg": "/Applications/ffmpeg",
    "metadata_cover_dimension": "320",
    "metadata_cover_embed": true,
    "cover_album_file": true,
    "extract_flac": false,
    "downloads_simultaneous_per_track_max": 20,
    "download_delay_sec_min": 3.0,
    "download_delay_sec_max": 5.0,
    "album_track_num_pad_min": 1,
    "downloads_concurrent_max": 3,
    "symlink_to_track": false,
    "playlist_create": false
}
```

**Comment by exislow** [comment]
Closed, since you have ignored all direction and did not provide any details to re-produce this.

**Comment by hajanet** [comment]
Same here, Video download is not working

**Comment by DJ-BAD** [comment]
I have a MacBook Pro M2, still happening with new update

**Comment by DJ-BAD** [comment]
https://drive.google.com/file/d/1lGXWboktJA95KozJSGEmabp8PRHoISxh/view?usp=share_link

Recorded the problem

**Comment by exislow** [comment]
Thanks for reporting this. It is fixed now.

**Comment by JohnStiles5** [comment]
Hello!

the problem still exists on my setup as well. it is the same OS Version as mentioned above.
