### ISSUE TITLE
[Bug] AttributeError: module 'ffmpeg' has no attribute 'input'

### ISSUE THREAD

**Issue by thr-4** [exislow/tidal-dl-ng#96]
### What happened?

When using the option to extract Flac, I get the following error: AttributeError: module 'ffmpeg' has no attribute 'input' with the last error message being:

`isrc = 'GBSG42300009'
path_file = '/tmp/tmpsd9ay0pw/2845e9f9-dc96-423e-92c8-4d0d16008953'
path_file_out = '/tmp/tmpsd9ay0pw/2845e9f9-dc96-423e-92c8-4d0d16008953.flac'
self = <tidal_dl_ng.download.Download object at 0x7ad8baac8d50>`

Path to ffmpeg should be set correctly.

### Version App

v0.13.1

### What operating system are you seeing the problem on?

Linux

### Your settings

```json
{"skip_existing": "False", "lyrics_embed": true, "lyrics_file": false, "video_download": true, "download_delay": true, "download_base_path": "~/Downloads/Tidal", "quality_audio": "
HI_RES_LOSSLESS", "quality_video": "480", "format_album": "{album_artist}/{album_title}/{track_volume_num}{album_track_num}-{track_title}", "format_playlist": "Playlists/{playlist_
name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}", "format_
video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": true, "path_binary_ffmpeg": "/usr/bin/ffmpeg", "metadata_cover_dimension": "1280", "extract_fla
c": true, "downgrade_on_hi_res": false}
```

**Comment by thr-4** [comment]
```
download.py:47 │
│ 6 in _extract_flac                                                                               │
│                                                                                                  │
│   473 │   def _extract_flac(self, path_file: str, isrc: str) -> str:                             │
│   474 │   │   path_file_out = path_file + AudioExtensions.FLAC                                   │
│   475 │   │   result, _ = (                                                                      │
│ ❱ 476 │   │   │   ffmpeg.input(path_file)                                                        │
│   477 │   │   │   .output(                                                                       │
│   478 │   │   │   │   path_file_out,                                                             │
│   479 │   │   │   │   map=0,                                                   
```

**Comment by exislow** [comment]
@thr-4 how did you install the app?

@menukaonline what OS are you running?

@all please post the full logs not just excerpts. Those snippets are of any benefit to analyze your problems. And I also need all the details to be able to re-produce it. Otherwise I cannot help.

**Comment by exislow** [comment]
https://github.com/exislow/tidal-dl-ng/releases/tag/v0.13.2 should fix this,

**Comment by thr-4** [comment]
Are any config changes required? Upgraded to v0.13.2 but issue still persists. No change in config.

**Comment by motlaghreyhan** [comment]
I had to `python3.11 -m pip ffmpeg-python`, and 'pip uninstall ffmpeg" to fix this. 

It was very temperamental for me for some reason, I may have forgotten to reload my terminal, but it took me a few attempts for this to work for me.

**Comment by thr-4** [comment]
@motlaghreyhan Interesting - I don't have any python-specific `ffmpeg` package installed, just the normal one installed via `apt`.

@exislow Here's the full output. Is there any other logfile I can provide?
```
╭─────────────────────────────────── Download Progress ───────────────────────────────────╮
│                                                                                         │
│                                                                                         │
│  List 'Australian Carnage - Live At T' ⠙ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0%  │
│  Item 'Nick Cave, Warren Ellis - Spin'   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100%  │
│                                                                                         │
│                                                                                         │
╰─────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/juro/.local/pipx/venvs/tidal-dl-ng/lib/python3.11/site-packages/tidal_dl_ng/cli.py:184 in  │
│ download                                                                                         │
│                                                                                                  │
│   181 │   │   │   │   │   media_id=item_id, media_type=media_type, file_template=file_template   │
│   182 │   │   │   │   )                                                                          │
│   183 │   │   │   elif media_type in [MediaType.ALBUM, MediaType.PLAYLIST, MediaType.MIX]:       │
│ ❱ 184 │   │   │   │   dl.items(                                                                  │
│   185 │   │   │   │   │   media_id=item_id,                                                      │
│   186 │   │   │   │   │   media_type=media_type,                                                 │
│   187 │   │   │   │   │   file_template=file_template,                                           │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │            ctx = <click.core.Context object at 0x78518c5b0250>                               │ │
│ │             dl = <tidal_dl_ng.download.Download object at 0x78518ba2b090>                    │ │
│ │  file_template = '{album_artist}/{album_title}/{track_volume_num}{album_track_num}-{track_t… │ │
│ │      file_urls = None                                                                        │ │
│ │      fn_logger = <tidal_dl_ng.helper.wrapper.LoggerWrapped object at 0x78518ba2bf10>         │ │
│ │           item = 'https://tidal.com/browse/album/307463371?u'                                │ │
│ │        item_id = '307463371'                                                                 │ │
│ │     media_type = <MediaType.ALBUM: 'album'>                                                  │ │
│ │       progress = <rich.progress.Progress object at 0x78518b692e10>                           │ │
│ │ progress_table = <rich.table.Table object at 0x78518ba28ed0>                                 │ │
│ │       settings = <tidal_dl_ng.config.Settings object at 0x78518b692990>                      │ │
│ │           urls = ['https://tidal.com/browse/album/307463371?u']                              │ │
│ │  urls_pos_last = 0                                                                           │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/juro/.local/pipx/venvs/tidal-dl-ng/lib/python3.11/site-packages/tidal_dl_ng/download.py:44 │
│ 7 in items                                                                                       │
│                                                                                                  │
│   444 │   │   while not self.progress.finished:                                                  │
│   445 │   │   │   for media in items:                                                            │
│   446 │   │   │   │   # Download the item.                                                       │
│ ❱ 447 │   │   │   │   status_download, result_path_file = self.item(                             │
│   448 │   │   │   │   │   media=media,                                                           │
│   449 │   │   │   │   │   file_template=file_name_relative,                                      │
│   450 │   │   │   │   │   quality_audio=quality_audio,                                           │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │     download_delay = True                                                                    │ │
│ │ file_name_relative = 'Nick Cave, Warren Ellis/Australian Carnage - Live At The Sydney Opera  │ │
│ │                      House/{tra'+45                                                          │ │
│ │      file_template = '{album_artist}/{album_title}/{track_volume_num}{album_track_num}-{tra… │ │
│ │              items = [                                                                       │ │
│ │                      │   <tidalapi.media.Track object at 0x78518ba28250>,                    │ │
│ │                      │   <tidalapi.media.Track object at 0x78518ba28a90>,                    │ │
│ │                      │   <tidalapi.media.Track object at 0x78518ba2ad90>,                    │ │
│ │                      │   <tidalapi.media.Track object at 0x78518ba387d0>,                    │ │
│ │                      │   <tidalapi.media.Track object at 0x78518b6bddd0>,                    │ │
│ │                      │   <tidalapi.media.Track object at 0x78518b6d5410>,                    │ │
│ │                      │   <tidalapi.media.Track object at 0x78518b6d55d0>,                    │ │
│ │                      │   <tidalapi.media.Track object at 0x78518b6d58d0>,                    │ │
│ │                      │   <tidalapi.media.Track object at 0x78518b6d5bd0>,                    │ │
│ │                      │   <tidalapi.media.Track object at 0x78518b6bff50>,                    │ │
│ │                      │   ... +8                                                              │ │
│ │                      ]                                                                       │ │
│ │    list_media_name = 'Australian Carnage - Live At T'                                        │ │
│ │              media = <tidalapi.media.Track object at 0x78518ba28250>                         │ │
│ │           media_id = '307463371'                                                             │ │
│ │         media_type = <MediaType.ALBUM: 'album'>                                              │ │
│ │            p_task1 = 0                                                                       │ │
│ │    progress_stdout = True                                                                    │ │
│ │      quality_audio = None                                                                    │ │
│ │      quality_video = None                                                                    │ │
│ │               self = <tidal_dl_ng.download.Download object at 0x78518ba2b090>                │ │
│ │     video_download = True                                                                    │ │
│ │     videos_include = True                                                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/juro/.local/pipx/venvs/tidal-dl-ng/lib/python3.11/site-packages/tidal_dl_ng/download.py:27 │
│ 3 in item                                                                                        │
│                                                                                                  │
│   270 │   │   │   │                                                                              │
│   271 │   │   │   │   # Extract FLAC from MP4 container using ffmpeg                             │
│   272 │   │   │   │   if isinstance(media, Track) and self.settings.data.extract_flac and do_f   │
│ ❱ 273 │   │   │   │   │   tmp_path_file = self._extract_flac(tmp_path_file, media.isrc)          │
│   274 │   │   │   │                                                                              │
│   275 │   │   │   │   # Move final file to the configured destination directory.                 │
│   276 │   │   │   │   os.makedirs(os.path.dirname(path_file), exist_ok=True)                     │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │    do_flac_extract = True                                                                    │ │
│ │     download_delay = False                                                                   │ │
│ │        file_exists = False                                                                   │ │
│ │     file_extension = <AudioExtensions.FLAC: '.flac'>                                         │ │
│ │ file_name_relative = 'Nick Cave, Warren Ellis/Australian Carnage - Live At The Sydney Opera  │ │
│ │                      House/101-'+46                                                          │ │
│ │      file_template = 'Nick Cave, Warren Ellis/Australian Carnage - Live At The Sydney Opera  │ │
│ │                      House/{tra'+45                                                          │ │
│ │              media = <tidalapi.media.Track object at 0x78518b976290>                         │ │
│ │           media_id = None                                                                    │ │
│ │         media_type = None                                                                    │ │
│ │          path_file = '/home/juro/Downloads/Tidal/Nick Cave, Warren Ellis/Australian Carnage  │ │
│ │                      - Live At '+78                                                          │ │
│ │      quality_audio = None                                                                    │ │
│ │      quality_video = None                                                                    │ │
│ │               self = <tidal_dl_ng.download.Download object at 0x78518ba2b090>                │ │
│ │       tmp_path_dir = '/tmp/tmpued7nh0f'                                                      │ │
│ │      tmp_path_file = '/tmp/tmpued7nh0f/f7f6ed1d-8bf3-4da0-bfc7-a780e4ee5d8b'                 │ │
│ │           uniquify = False                                                                   │ │
│ │     video_download = True                                                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/juro/.local/pipx/venvs/tidal-dl-ng/lib/python3.11/site-packages/tidal_dl_ng/download.py:47 │
│ 6 in _extract_flac                                                                               │
│                                                                                                  │
│   473 │   def _extract_flac(self, path_file: str, isrc: str) -> str:                             │
│   474 │   │   path_file_out = path_file + AudioExtensions.FLAC                                   │
│   475 │   │   result, _ = (                                                                      │
│ ❱ 476 │   │   │   ffmpeg.input(path_file)                                                        │
│   477 │   │   │   .output(                                                                       │
│   478 │   │   │   │   path_file_out,                                                             │
│   479 │   │   │   │   map=0,                                                                     │
│                                                                                                  │
│ ╭─────────────────────────────────── locals ───────────────────────────────────╮                 │
│ │          isrc = 'GBSG42300009'                                               │                 │
│ │     path_file = '/tmp/tmpued7nh0f/f7f6ed1d-8bf3-4da0-bfc7-a780e4ee5d8b'      │                 │
│ │ path_file_out = '/tmp/tmpued7nh0f/f7f6ed1d-8bf3-4da0-bfc7-a780e4ee5d8b.flac' │                 │
│ │          self = <tidal_dl_ng.download.Download object at 0x78518ba2b090>     │                 │
│ ╰──────────────────────────────────────────────────────────────────────────────╯                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by thr-4** [comment]
> @thr-4 how did you install the app?

My distro (Ubuntu) forces me to use `pipx` so I used that. I am wondering if this is causing the issue.

**Comment by juxuanu** [comment]
@thr-4 does the latest version work with pipx? I am getting

```
PIP STDOUT
----------

PIP STDERR
----------
ERROR: Ignored the following versions that require a different python version: 0.10.0 Requires-Python <3.12,>=3.10; 0.10.1 Requires-Python <3.12,>=3.10; 0.10.2 Requires-Python <3.12,>=3.10; 0.11.0 Requires-Python <3.12,>=3.10; 0.12.0 Requires-Python <3.12,>=3.10; 0.12.1 Requires-Python <3.12,>=3.10; 0.12.2 Requires-Python <3.12,>=3.10; 0.12.3 Requires-Python <3.12,>=3.10; 0.12.4 Requires-Python <3.12,>=3.10; 0.12.5 Requires-Python <3.12,>=3.10; 0.12.6 Requires-Python <3.12,>=3.10; 0.12.7 Requires-Python <3.12,>=3.10; 0.13.0 Requires-Python <3.12,>=3.10; 0.13.1 Requires-Python <3.12,>=3.10; 0.13.2 Requires-Python <3.12,>=3.10; 0.14.0 Requires-Python <3.12,>=3.10; 0.15.0 Requires-Python <3.12,>=3.10; 0.15.1 Requires-Python <3.12,>=3.10; 0.15.2 Requires-Python <3.12,>=3.10; 0.15.3 Requires-Python <3.12,>=3.10; 0.15.4 Requires-Python <3.12,>=3.10; 0.15.5 Requires-Python <3.12,>=3.10; 0.15.6 Requires-Python <3.12,>=3.10; 0.20.0 Requires-Python <3.13,>=3.10; 0.20.1 Requires-Python <3.13,>=3.10; 0.20.2 Requires-Python <3.13,>=3.10; 0.20.3 Requires-Python <3.13,>=3.10; 0.21.2 Requires-Python <3.13,>=3.10; 0.21.3 Requires-Python <3.13,>=3.10; 0.21.4 Requires-Python <3.13,>=3.10; 0.22.0 Requires-Python <3.13,>=3.10; 0.23.0 Requires-Python <3.13,>=3.10; 0.4.10 Requires-Python >=3.10,<3.12; 0.4.11 Requires-Python >=3.10,<3.12; 0.4.13 Requires-Python >=3.10,<3.12; 0.4.14 Requires-Python >=3.10,<3.12; 0.4.15 Requires-Python >=3.10,<3.12; 0.4.16 Requires-Python >=3.10,<3.12; 0.4.17 Requires-Python >=3.10,<3.12; 0.4.18 Requires-Python >=3.10,<3.12; 0.4.19 Requires-Python >=3.10,<3.12; 0.4.2 Requires-Python >=3.10,<3.12; 0.4.20 Requires-Python >=3.10,<3.12; 0.4.21 Requires-Python >=3.10,<3.12; 0.4.22 Requires-Python >=3.10,<3.12; 0.4.23 Requires-Python >=3.10,<3.12; 0.4.24 Requires-Python >=3.10,<3.12; 0.4.25 Requires-Python >=3.10,<3.12; 0.4.26 Requires-Python >=3.10,<3.12; 0.4.27 Requires-Python >=3.10,<3.12; 0.4.28 Requires-Python >=3.10,<3.12; 0.4.29 Requires-Python >=3.10,<3.12; 0.4.3 Requires-Python >=3.10,<3.12; 0.4.30 Requires-Python >=3.10,<3.12; 0.4.31 Requires-Python >=3.10,<3.12; 0.4.32 Requires-Python >=3.10,<3.12; 0.4.4 Requires-Python >=3.10,<3.12; 0.4.5 Requires-Python >=3.10,<3.12; 0.4.6 Requires-Python >=3.10,<3.12; 0.4.7 Requires-Python >=3.10,<3.12; 0.4.8 Requires-Python >=3.10,<3.12; 0.4.9 Requires-Python >=3.10,<3.12; 0.5.0 Requires-Python >=3.10,<3.12; 0.5.1 Requires-Python >=3.10,<3.12; 0.6.0 Requires-Python >=3.10,<3.12; 0.7.0 Requires-Python >=3.10,<3.12; 0.7.1 Requires-Python >=3.10,<3.12; 0.8.0 Requires-Python >=3.10,<3.12; 0.8.1 Requires-Python >=3.10,<3.12; 0.8.2 Requires-Python >=3.10,<3.12; 0.8.3 Requires-Python >=3.10,<3.12; 0.9.0 Requires-Python <3.12,>=3.10; 0.9.1 Requires-Python <3.12,>=3.10
ERROR: Could not find a version that satisfies the requirement tidal-dl-ng[gui] (from versions: none)
ERROR: No matching distribution found for tidal-dl-ng[gui]
```

**Comment by thr-4** [comment]
> @thr-4 does the latest version work with pipx? I am getting
> 
> ```
> PIP STDOUT
> ----------
> 
> PIP STDERR
> ----------
> ERROR: Ignored the following versions that require a different python version: 0.10.0 Requires-Python <3.12,>=3.10; 0.10.1 Requires-Python <3.12,>=3.10; 0.10.2 Requires-Python <3.12,>=3.10; 0.11.0 Requires-Python <3.12,>=3.10; 0.12.0 Requires-Python <3.12,>=3.10; 0.12.1 Requires-Python <3.12,>=3.10; 0.12.2 Requires-Python <3.12,>=3.10; 0.12.3 Requires-Python <3.12,>=3.10; 0.12.4 Requires-Python <3.12,>=3.10; 0.12.5 Requires-Python <3.12,>=3.10; 0.12.6 Requires-Python <3.12,>=3.10; 0.12.7 Requires-Python <3.12,>=3.10; 0.13.0 Requires-Python <3.12,>=3.10; 0.13.1 Requires-Python <3.12,>=3.10; 0.13.2 Requires-Python <3.12,>=3.10; 0.14.0 Requires-Python <3.12,>=3.10; 0.15.0 Requires-Python <3.12,>=3.10; 0.15.1 Requires-Python <3.12,>=3.10; 0.15.2 Requires-Python <3.12,>=3.10; 0.15.3 Requires-Python <3.12,>=3.10; 0.15.4 Requires-Python <3.12,>=3.10; 0.15.5 Requires-Python <3.12,>=3.10; 0.15.6 Requires-Python <3.12,>=3.10; 0.20.0 Requires-Python <3.13,>=3.10; 0.20.1 Requires-Python <3.13,>=3.10; 0.20.2 Requires-Python <3.13,>=3.10; 0.20.3 Requires-Python <3.13,>=3.10; 0.21.2 Requires-Python <3.13,>=3.10; 0.21.3 Requires-Python <3.13,>=3.10; 0.21.4 Requires-Python <3.13,>=3.10; 0.22.0 Requires-Python <3.13,>=3.10; 0.23.0 Requires-Python <3.13,>=3.10; 0.4.10 Requires-Python >=3.10,<3.12; 0.4.11 Requires-Python >=3.10,<3.12; 0.4.13 Requires-Python >=3.10,<3.12; 0.4.14 Requires-Python >=3.10,<3.12; 0.4.15 Requires-Python >=3.10,<3.12; 0.4.16 Requires-Python >=3.10,<3.12; 0.4.17 Requires-Python >=3.10,<3.12; 0.4.18 Requires-Python >=3.10,<3.12; 0.4.19 Requires-Python >=3.10,<3.12; 0.4.2 Requires-Python >=3.10,<3.12; 0.4.20 Requires-Python >=3.10,<3.12; 0.4.21 Requires-Python >=3.10,<3.12; 0.4.22 Requires-Python >=3.10,<3.12; 0.4.23 Requires-Python >=3.10,<3.12; 0.4.24 Requires-Python >=3.10,<3.12; 0.4.25 Requires-Python >=3.10,<3.12; 0.4.26 Requires-Python >=3.10,<3.12; 0.4.27 Requires-Python >=3.10,<3.12; 0.4.28 Requires-Python >=3.10,<3.12; 0.4.29 Requires-Python >=3.10,<3.12; 0.4.3 Requires-Python >=3.10,<3.12; 0.4.30 Requires-Python >=3.10,<3.12; 0.4.31 Requires-Python >=3.10,<3.12; 0.4.32 Requires-Python >=3.10,<3.12; 0.4.4 Requires-Python >=3.10,<3.12; 0.4.5 Requires-Python >=3.10,<3.12; 0.4.6 Requires-Python >=3.10,<3.12; 0.4.7 Requires-Python >=3.10,<3.12; 0.4.8 Requires-Python >=3.10,<3.12; 0.4.9 Requires-Python >=3.10,<3.12; 0.5.0 Requires-Python >=3.10,<3.12; 0.5.1 Requires-Python >=3.10,<3.12; 0.6.0 Requires-Python >=3.10,<3.12; 0.7.0 Requires-Python >=3.10,<3.12; 0.7.1 Requires-Python >=3.10,<3.12; 0.8.0 Requires-Python >=3.10,<3.12; 0.8.1 Requires-Python >=3.10,<3.12; 0.8.2 Requires-Python >=3.10,<3.12; 0.8.3 Requires-Python >=3.10,<3.12; 0.9.0 Requires-Python <3.12,>=3.10; 0.9.1 Requires-Python <3.12,>=3.10
> ERROR: Could not find a version that satisfies the requirement tidal-dl-ng[gui] (from versions: none)
> ERROR: No matching distribution found for tidal-dl-ng[gui]
> ```
> 
> This is on Arch, Python 3.13.1

I have moved over to the Windows version since, haven't tried in Linux in a while.
